// auth
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const LOGOUT_USER = "LOGOUT_USER";

// ui
export const CLIENT_LOADED = "CLIENT_LOADED";
export const CHANGE_TAB = "CHANGE_TAB";
export const TOGGLE_AUTO_DELETE = "TOGGLE_AUTO_DELETE";
export const PLAYLISTS_LOADER = "PLAYLISTS_LOADER";
export const PLAYLISTS_UPDATE_BADGE = "PLAYLISTS_UPDATE_BADGE";
export const PLAYLISTS_UPDATE_BADGE_PLUS = "PLAYLISTS_UPDATE_BADGE_PLUS";
export const PLAYLISTS_UPDATE_BADGE_MINUS = "PLAYLISTS_UPDATE_BADGE_MINUS";

// send notifications to user
export const SNACK_WRITE = "SNACK_WRITE";
export const SNACK_CLEAR = "SNACK_CLEAR";

// connects YouTube API
export const GET_PLAYLISTS = "GET_PLAYLISTS";
export const CREATE_PLAYLIST = "CREATE_PLAYLIST";
export const DELETE_PLAYLIST = "DELETE_PLAYLIST";
export const UPDATE_PLAYLIST = "UPDATE_PLAYLIST";
export const GET_PLAYLIST_ITEMS = "GET_PLAYLIST_ITEMS";
export const DELETE_PLAYLIST_ITEM = "DELETE_PLAYLIST_ITEM";

// provides UI update while sending API requests above
export const UI_PLAYLIST_PLAY = "UI_PLAYLIST_PLAY";
export const UI_PLAYLIST_CLEAR = "UI_PLAYLIST_CLEAR";
export const UI_PLAYLIST_DELETE = "UI_PLAYLIST_DELETE";
export const UI_PLAYLIST_UPDATE = "UI_PLAYLIST_UPDATE";
export const UI_PLAYLIST_ITEM_PLAY = "UI_PLAYLIST_ITEM_PLAY";
export const UI_PLAYLIST_ITEM_CLEAR = "UI_PLAYLIST_ITEM_CLEAR";
export const UI_PLAYLIST_ITEM_DELETE = "UI_PLAYLIST_ITEM_DELETE";
export const UI_RESET_ALL_IDS = "UI_RESET_ALL_IDS";
